name: dogs_and_cats
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.1.2
  intl: ^0.18.1
  shimmer: ^2.0.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  flutter_hooks: ^0.18.5+1
  shared_preferences: ^2.0.15
  bloc_test: ^9.1.0
  firebase_auth_mocks: ^0.12.0
  mock_exceptions: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

flutter_intl:
  enabled: true